let createVideoClip;
if (browser.isIOS) {
  createVideoClip = {
    createButton: "~Create, tab, 3 of 5",
    addVideoClipBtn : `~add-AIAgent`,
    addClipBtn : `//XCUIElementTypeOther[@name="Add"]`,
    videoClipSuccessMsg : `~Your AI Funnel Created Successfully!`,
    typeVisible : `//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[6]/android.view.ViewGroup[3]/com.horcrux.svg.SvgView/com.horcrux.svg.GroupView`,
    cameraButton: "~Camera",
    allowButton: "id:com.android.permissioncontroller:id/permission_allow_button",
    galleryButtonId: `//XCUIElementTypeButton[@name="Gallery"]`,
    thumbnailImageXPath: `//XCUIElementTypeImage[@name="Video, fourteen seconds, January 01, 1970, 5:30 AM"]`,
    shutterButton: "accessibility id:Shutter button",
    doneButton: "accessibility id:Done",
    nameInput: "~video-cliptitle",
    saveButton: "~saving-videoclip",
    explainerButton: "xpath://android.widget.TextView[@text=\"Explainer 1\"]",
    descriptionField : `~videoclip-description`,
    needToEngageBtn : `~need-engage`,
    engageYesBtn : `~selectedInput-1`,
    engageNoBtn : `~selectedInput-0`,
    multiChoiceBtn : `~Multi Choice`,
    textChoiceBtn : `~Text`,
    normalTextChoiceBtn : `~Normal Text`,
    multilineTextChoiceBtn : `~Multiline Text`,
    phoneTextChoiceBtn : `~Phone Number`,
    emailTextChoiceBtn : `~Email`,
    addressTextChoiceBtn : `~Address`,
    buttonChoiceBtn : `~Button`,
    ImageChoiceBtn : `~Image`,
    VideoChoiceBtn : `~Video`,
    AudioChoiceBtn : `~Audio`,
    feedbackStarChoiceBtn : `~Feedback Star`,
    openQuestionChoiceBtn : `~Open Question`,
    feedbackScaleChoiceBtn : `~Feedback Scale`,
    branchingChoiceBtn : `~Branching`,
    detailsFormChoiceBtn : `~Details Form`,
    multiNoBtn : `//XCUIElementTypeOther[@name="addmulti-click" and @label="No"]`,
    multiYesBtn : `//XCUIElementTypeOther[@name="addmulti-click" and @label="Yes"]`,
    option1Field : `~addoption_0`,
    addoptionBtn : `~addoption-click`,
    option2Field : `~addoption_1`,
    option3Field : `~addoption_2`,
    option4Field : `~addoption_3`,
    option5Field : `~addoption_4`,
    option6Field : `~addoption_5`,
    option7Field : `~addoption_6`,
    option8Field : `~addoption_7`,
    option9Field : `~addoption_8`,
    option10Field : `~addoption_9`,
    saveOptionBtn : `~option-save`,
    multiScreenBack : `~option-back`,
    multiCreationCheck : `~select-options`,
    mediaDeleteBtn : `~delete-media`,
    buttonTypeSelectionBtn : `~buttonList-click`,
    buttonText : `~Link`,
    buttonEmailText : `~Email`,
    buttonPhoneText : `~Phone Number`,
    buttonContact : `~Contact`,
    buttonLinkLabelField : `~labelId_0`,
    buttonLinkValueField : `~valueId_0`,
    buttonTypeAddBtn : `~add_btntype`,
    buttonTypeRemoveBtn : `~removetype_0`,
    ButtonTypeSaveBtn : `~save-type`,
    buttonTypeBackOption : `~type-back`,
    buttonTypeSelection2 : `(//XCUIElementTypeOther[@name = "buttonList-click"])[2]`,
    buttonEmaillabelField : `~labelId_1`,
    buttonEmailValueField : `~valueId_1`,
    buttonTypeSelection3 : `(//XCUIElementTypeOther[@name = "buttonList-click"])[3]`,
    buttonPhonelabelField : `~labelId_2`,
    buttonPhoneValueField : `~valueId_2`,
    buttonTypeSelection4 : `(//XCUIElementTypeOther[@name = "buttonList-click"])[4]`,
    buttonContactlabelField : `~labelId_3`,
    buttonContactProfileBtn : `~select-contact`,
    profileName : `~company-name`,
    profileNumber : `~contact-number`,
    profileEmail : `~email-select`,
    profileWebUrl : `~website-url`,
    profileSupportUrl : `~support-url`,
    profileNotes : `~profile-notes`,
    profileSaveBtn : `~profile-save`,
    profileBackBtn : `~contact-back`,
    branchOkButton : `~Ok`,
    branchingAddBtn : `~Add`,
    branchName : `~addVideoClipText-0`,
    addBranchVideoClipBtn : `~addVideoClipBtn-0`,
    branchClipBtn : `~select-branch`,
    formNameField : `~form-name`,
    caprchaEnableBtn : `~enable-captcha`,
    termsEnableBtn : `~enable-terms`,
    form1Lable : `~formlabel_0`,
    form1InputType : `~form-select`,
    form1RequiredField : `~required-click`,
    formAddBtn : `~addform-click`,
    formTextSelect : `~selectedtype-0`,
    formNumericSelect : `~selectedtype-1`,
    formDataSelect : `~selectedtype-2`,
    formAddressSelect : `~selectedtype-3`,
    fromEmailSelect : `~selectedtype-4`,
    formPhoneSelect : `~selectedtype-5`,
    formYesType : `~selectedtype-0`,
    formNoType : `~selectedtype-1`,
    formSelectTypeBack : `~formtype-back`,
    linkDisplayTextField : `(//XCUIElementTypeOther[@name="Link Display Text"])[5]/XCUIElementTypeOther[2]/XCUIElementTypeTextField`,
    policyLinkTextField : `(//XCUIElementTypeOther[@name="Terms & Conditions policyLink"])[1]/XCUIElementTypeOther[2]/XCUIElementTypeTextField`,
    formRemovebtn : `~removeform_0`,
    createFormSaveBtn : `~form-save`,
    engageFormBackBtn : `~form-back`,
    engageTypeBackBtn : `~formscreen-back`,
    formTypeBtn : `~meta-click`,
    createdForm1 : `~formselect-0`,
    clipSelect1 : `//XCUIElementTypeOther[@name="videoclip-click"]`,
    editBtn : `~videoclip-editclick`,
    updateVideoClipTileField : `~video-cliptitle`,
    updateVideoClipDescriptionField : `~videoclip-description`,
    tagButton : `(//XCUIElementTypeOther[@name="Tags"])[1]`,
    buttonTypeField : `~select-button`,
    saveTagBtn : `~tag-save`,
    updateVideoClipBtn : `~update-videoclip`,
    deleteVideoClipBtn : `~videoclip-delete`,
    updateScreenBackBtn : `~videoclip-back`,
    confrimDeleteBtn : `~OK`
  };
} else if (browser.isAndroid) {
  createVideoClip = {
    createButton: "xpath://android.widget.TextView[@text=\"Create\"]",
    addVideoClipBtn : `//android.widget.TextView[@text="Add Video Clip"]`,
    addClipBtn : `//android.widget.TextView[@text="Add"]`,
    videoClipSuccessMsg : `//android.widget.TextView[@text="New Video Clip Successfully Created!"]`,
    typeVisible : `//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[6]/android.view.ViewGroup[3]/com.horcrux.svg.SvgView/com.horcrux.svg.GroupView`,
    cameraButton: "id:android:id/button2",
    allowButton: "id:com.android.permissioncontroller:id/permission_allow_button",
    galleryButtonId: "id:android:id/button1",
    thumbnailImageXPath: "(//android.widget.ImageView[@resource-id=\"com.google.android.providers.media.module:id/icon_thumbnail\"])[1]",
    shutterButton: "accessibility id:Shutter button",
    doneButton: "accessibility id:Done",
    nameInput: "xpath://android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[3]/android.view.ViewGroup/android.widget.EditText",
    saveButton: "xpath://android.widget.TextView[@text=\"Save\"]",
    explainerButton: "xpath://android.widget.TextView[@text=\"Explainer 1\"]",
    descriptionField : `//android.widget.EditText[@resource-id="videoclip-description"]`,
    needToEngageBtn : `//android.widget.TextView[@text="Need to Engage?"]`,
    engageYesBtn : `//android.view.ViewGroup[@resource-id="selectedInput-1"]`,
    engageNoBtn : `//android.view.ViewGroup[@resource-id="selectedInput-0"]`,
    multiChoiceBtn : `//android.widget.TextView[@text="Multi Choice"]`,
    textChoiceBtn : `//android.widget.TextView[@text="Text"]`,
    normalTextChoiceBtn : `//android.widget.TextView[@text="Normal Text"]`,
    multilineTextChoiceBtn : `//android.widget.TextView[@text="Multiline Text"]`,
    phoneTextChoiceBtn : `//android.widget.TextView[@text="Phone Number"]`,
    emailTextChoiceBtn : `//android.widget.TextView[@text="Email"]`,
    addressTextChoiceBtn : `//android.widget.TextView[@text="Address"]`,
    buttonChoiceBtn : `//android.widget.TextView[@text="Button"]`,
    ImageChoiceBtn : `//android.widget.TextView[@text="Image"]`,
    VideoChoiceBtn : `//android.widget.TextView[@text="Video"]`,
    AudioChoiceBtn : `//android.widget.TextView[@text="Audio"]`,
    feedbackStarChoiceBtn : `//android.widget.TextView[@text="Feedback Star"]`,
    openQuestionChoiceBtn : `//android.widget.TextView[@text="Open Question"]`,
    feedbackScaleChoiceBtn : `//android.widget.TextView[@text="Feedback Scale"]`,
    branchingChoiceBtn : `//android.widget.TextView[@text="Branching"]`,
    detailsFormChoiceBtn : `//android.widget.TextView[@text="Details Form"]`,
    multiNoBtn : `(//android.view.ViewGroup[@resource-id="addmulti-click"])[1]`,
    multiYesBtn : `(//android.view.ViewGroup[@resource-id="addmulti-click"])[2]`,
    option1Field : `//android.widget.EditText[@resource-id="addoption_0"]`,
    addoptionBtn : `//android.widget.TextView[@text="Add"]`,
    option2Field : `//android.widget.EditText[@resource-id="addoption_1"]`,
    option3Field : `//android.widget.EditText[@resource-id="addoption_2"]`,
    option4Field : `//android.widget.EditText[@resource-id="addoption_3"]`,
    option5Field : `//android.widget.EditText[@resource-id="addoption_4"]`,
    option6Field : `//android.widget.EditText[@resource-id="addoption_5"]`,
    option7Field : `//android.widget.EditText[@resource-id="addoption_6"]`,
    option8Field : `//android.widget.EditText[@resource-id="addoption_7"]`,
    option9Field : `//android.widget.EditText[@resource-id="addoption_8"]`,
    option10Field : `//android.widget.EditText[@resource-id="addoption_9"]`,
    saveOptionBtn : `//android.view.ViewGroup[@resource-id="option-save"]`,
    multiScreenBack : `//android.view.ViewGroup[@resource-id="option-back"]`,
    multiCreationCheck : `(//android.widget.TextView[@text="Multi"])[1]`,
    mediaDeleteBtn : `//android.view.ViewGroup[@resource-id="delete-media"]`,
    buttonTypeSelectionBtn : `//android.view.ViewGroup[@resource-id="buttonList-click"]`,
    buttonText : `//android.widget.TextView[@text="Link"]`,
    buttonEmailText : `//android.widget.TextView[@text="Email"]`,
    buttonPhoneText : `//android.widget.TextView[@text="Phone Number"]`,
    buttonContact : `//android.widget.TextView[@text="Contact"]`,
    buttonLinkLabelField : `//android.widget.EditText[@resource-id="labelId_0"]`,
    buttonLinkValueField : `//android.widget.EditText[@resource-id="valueId_0"]`,
    buttonTypeAddBtn : `//android.view.ViewGroup[@resource-id="add_btntype"]`,
    buttonTypeRemoveBtn : `//android.view.ViewGroup[@resource-id="removetype_0"]`,
    ButtonTypeSaveBtn : `//android.view.ViewGroup[@resource-id="save-type"]`,
    buttonTypeBackOption : `//android.view.ViewGroup[@resource-id="type-back"]`,
    buttonTypeSelection2 : `(//android.view.ViewGroup[@resource-id="buttonList-click"])[2]`,
    buttonEmaillabelField : `//android.widget.EditText[@resource-id="labelId_1"]`,
    buttonEmailValueField : `//android.widget.EditText[@resource-id="valueId_1"]`,
    buttonTypeSelection3 : `(//android.view.ViewGroup[@resource-id="buttonList-click"])[3]`,
    buttonPhonelabelField : `//android.widget.EditText[@resource-id="labelId_2"]`,
    buttonPhoneValueField : `//android.widget.EditText[@resource-id="valueId_2"]`,
    buttonTypeSelection4 : `(//android.view.ViewGroup[@resource-id="buttonList-click"])[4]`,
    buttonContactlabelField : `//android.widget.EditText[@resource-id="labelId_3"]`,
    buttonContactProfileBtn : `//android.view.ViewGroup[@resource-id="select-contact"]`,
    profileName : `//android.widget.EditText[@resource-id="company-name"]`,
    profileNumber : `//android.widget.EditText[@resource-id="contact-number"]`,
    profileEmail : `//android.widget.EditText[@resource-id="email-select"]`,
    profileWebUrl : `//android.widget.EditText[@resource-id="website-url"]`,
    profileSupportUrl : `//android.widget.EditText[@resource-id="support-url"]`,
    profileNotes : `//android.widget.EditText[@resource-id="profile-notes"]`,
    profileSaveBtn : `//android.view.ViewGroup[@resource-id="profile-save"]`,
    profileBackBtn : `//android.view.ViewGroup[@resource-id="contact-back"]`,
    branchOkButton : `//android.widget.TextView[@text="Ok"]`,
    branchingAddBtn : `//android.widget.TextView[@text="Add"]`,
    branchName : `//android.widget.EditText`,
    addBranchVideoClipBtn : `//android.widget.TextView[@text=" Add Video Clip"]`,
    branchClipBtn : `//android.view.ViewGroup[@resource-id="select-branch"]`,
    formNameField : `//android.widget.EditText[@resource-id="form-name"]`,
    caprchaEnableBtn : `//android.view.ViewGroup[@resource-id="enable-captcha"]`,
    termsEnableBtn : `//android.view.ViewGroup[@resource-id="enable-terms"]`,
    form1Lable : `//android.widget.EditText[@resource-id="formlabel_0"]`,
    form1InputType : `//android.view.ViewGroup[@resource-id="form-select"]`,
    form1RequiredField : `//android.view.ViewGroup[@resource-id="required-click"]`,
    formAddBtn : `//android.view.ViewGroup[@resource-id="add-form"]`,
    formTextSelect : `//android.widget.TextView[@text="Text"]`,
    formNumericSelect : `//android.widget.TextView[@text="Numeric"]`,
    formDataSelect : `//android.widget.TextView[@text="Date Picker"]`,
    formAddressSelect : `//android.widget.TextView[@text="Address"]`,
    fromEmailSelect : `//android.widget.TextView[@text="Email"]`,
    formPhoneSelect : `//android.widget.TextView[@text="Phone"]`,
    formYesType : `//android.widget.TextView[@text="Yes"]`,
    formNoType : `//android.widget.TextView[@text="No"]`,
    formSelectTypeBack : `//android.view.ViewGroup[@resource-id="formtype-back"]`,
    linkDisplayTextField : `//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]/android.view.ViewGroup/android.widget.EditText`,
    policyLinkTextField : `//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[6]/android.view.ViewGroup/android.view.ViewGroup/android.widget.EditText`,
    formRemovebtn : `//android.view.ViewGroup[@resource-id="removeform_0"]`,
    createFormSaveBtn : `//android.view.ViewGroup[@resource-id="form-save"]`,
    engageFormBackBtn : `//android.view.ViewGroup[@resource-id="formscreen-back"]`,
    engageTypeBackBtn : `//com.horcrux.svg.SvgView`,
    formTypeBtn : `//android.view.ViewGroup[@resource-id="meta-click"]`,
    createdForm1 : `//android.view.ViewGroup[@resource-id="formselect-0"]`,
    clipSelect1 : `//android.view.ViewGroup[@resource-id="videoclip-click"]`,
    editBtn : `//android.view.ViewGroup[@resource-id="videoclip-editclick"]`,
    updateVideoClipTileField : `//android.widget.EditText[@resource-id="video-cliptitle"]`,
    updateVideoClipDescriptionField : `//android.widget.EditText[@resource-id="videoclip-description"]`,
    tagButton : `//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[11]`,
    buttonTypeField : `//android.view.ViewGroup[@resource-id="select-button"]`,
    saveTagBtn : `//android.view.ViewGroup[@resource-id="tag-save"]`,
    updateVideoClipBtn : `//android.view.ViewGroup[@resource-id="update-videoclip"]`,
    deleteVideoClipBtn : `//android.view.ViewGroup[@resource-id="videoclip-delete"]`,
    updateScreenBackBtn : `//android.view.ViewGroup[@resource-id="videoclip-backclick"]`,
    confrimDeleteBtn : `//android.widget.Button[@resource-id="android:id/button1"]`
  };
}
export default createVideoClip;