let forgotPassword;
if (browser.isIOS) {
  forgotPassword = {
    forgotPasswordButton: '~forgot-password-click',
    forgotPasswordInputField: '~forgot_password',
    forgotPasswordScreenContentVerify1: '//XCUIElementTypeStaticText[@name="Drank too much last night, huh?"]',
    forgotPasswordBackButton: '~forgot-back',
    sendButton: '~forgot-send',
    otpScreenContentCheck1: '//XCUIElementTypeStaticText[@name="We’ve just send you 4 digits code to your q1@yopmail.com"]',
    otpScreenContentCheck2: '//XCUIElementTypeStaticText[@name="OTP Verification"]',
    otpInputField1: '~otp-field0',
    otpInputField2: '~otp-field1',
    otpInputField3: '~otp-field2',
    otpInputField4: '~otp-field3',
    verifyButton: '~Verify',
    otpBackButton: '~otp-back',
    changePasswordScreenContent1: '//XCUIElementTypeStaticText[@name="Your new password must be different from previous used passwords"]',
    changePasswordScreenContent2: '//XCUIElementTypeStaticText[@name="Change Password"]',
    backBtn: '~changepassword-back',
    passwordField: '~change-new',
    confirmPasswordField: '~change-password',
    saveBtn: '~changepassword-save',
    changePasswordErrorMsg: '//XCUIElementTypeStaticText[@name="This field is required"]',
    invalidOtpToast : `//android.widget.Toast`,
    changePasswordErrorMsg1: '//XCUIElementTypeStaticText[@name="Password does not match"]',
    changePasswordErrorMsg2: `//XCUIElementTypeStaticText[@name="Password must be at least 6 characters long"]`,
  };
} else if (browser.isAndroid) {
  forgotPassword = {
    forgotPasswordButton: 'xpath://android.widget.TextView[@text="Forgot Password?"]',
    forgotPasswordInputField: 'class name:android.widget.EditText',
    forgotPasswordScreenContentVerify1: 'xpath://android.widget.TextView[@text="Drank too much last night, huh?"]',
    forgotPasswordBackButton: 'xpath://android.widget.FrameLayout[@resource-id=\"android:id/content\"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]',
    sendButton: 'xpath://android.widget.TextView[@text="Send"]',
    otpScreenContentCheck1: 'xpath://android.widget.TextView[@text="We’ve just sent you 4 digits code to your q1@yopmail.com"]',
    otpScreenContentCheck2: 'xpath://android.widget.TextView[@text="OTP Verification"]',
    otpInputField1: 'xpath://android.widget.EditText[@resource-id="otp-field0"]',
    otpInputField2: 'xpath://android.widget.EditText[@resource-id="otp-field1"]',
    otpInputField3: 'xpath://android.widget.EditText[@resource-id="otp-field2"]',
    otpInputField4: 'xpath://android.widget.EditText[@resource-id="otp-field3"]',
    verifyButton: 'xpath://android.widget.TextView[@text="Verify"]',
    otpBackButton: 'xpath://android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]/com.horcrux.svg.SvgView',
    changePasswordScreenContent1: 'xpath://android.widget.TextView[contains(@text, "Your new password must be different from previous used passwords")]',
    changePasswordScreenContent2: 'xpath://android.widget.TextView[contains(@text, "Change Password")]',
    backBtn: '//android.view.ViewGroup[@resource-id="changepassword-back"]',
    passwordField: 'xpath://android.widget.EditText[@resource-id="change-new"]',
    confirmPasswordField: 'xpath://android.widget.EditText[@resource-id="change-password"]',
    saveBtn: 'xpath://android.widget.TextView[@text="Save"]',
    changePasswordErrorMsg: 'xpath://android.widget.TextView[@text="This field is required"]',
    invalidOtpToast : `//android.widget.Toast`,
    changePasswordErrorMsg1: 'xpath://android.widget.TextView[@text="Password does not match"]',
    changePasswordErrorMsg2: 'xpath://android.widget.TextView[@text="Password must be at least 6 characters long"]',
  };  
}
export default forgotPassword;