let loginConstants;
console.log(browser.isIOS,)
if (browser.isIOS) {
  loginConstants = {
    welcomeScreenVerify1 : `~Welcome to AdaptiveFunnels AI`,
    welcomeScreenVerify2 : `~Hi there, Enter your credentials to proceed.`,
    getStartedBtn : `~login-click`,
    googleBtn : `~google-login`,
    loginContentVerify1 : `~Welcome to AdaptiveFunnels AI`,
    loginContentVerify2 : `~Hi there, Enter your credentials to proceed.`,
    emailField : `~login-email`,
    passwordField : `~login-password`,
    forgotPasswordField : `~forgot-password-click`,
    loginBtn : `~login-button`,
    signUpButton : `~signup-click`,
    loginBackBtn : `~login`,
    passwordEyeIcon : `~show-password`,
    emptyFieldCheck : `(//XCUIElementTypeStaticText[@name="This field is required"])[1]`,
    bothEmptyMailField : `(//XCUIElementTypeStaticText[@name="This field is required"])[1]`,
    bothEmptyPasswordField : `(//XCUIElementTypeStaticText[@name="This field is required"])[2]`,
    phoneNumerPrefix : `//XCUIElementTypeOther[@name="+1"]`,
    emailPrefix : `(//XCUIElementTypeOther[@name="Enter Mobile Number / Email ID"])[2]/XCUIElementTypeOther[2]`,
    phoneNumberLengthValidateMsg : `//XCUIElementTypeStaticText[@name="Please enter a valid Phone Number"]`,
    phoneNumberLengthValidateMsg1 : `//XCUIElementTypeStaticText[@name="Please enter a valid Phone Number"]`,
    invalidMailCheck1 : `//XCUIElementTypeStaticText[@name="Please enter a valid email address"]`,
    invalidMailCheck : `//XCUIElementTypeStaticText[@name="Please enter a valid email address"]`,
    invalidMailPasswordMail : `//*[@name="Invalid email/password"]`,
    loginVerify : `~AI Funnels, tab, 1 of 5`,
    profileBtn : `~home-profile`,
    logoutBtn : `~Logoutclick`,
    logoutConfrimBtn : `~OK`,
    profileScreenVerify : `//XCUIElementTypeStaticText[@name="Profile"]`,
    welcomeScreenVerify3 : `//android.widget.TextView[@text="New to AI Agent?"]`,
    welcomeScreenVerify4 : '~signup',
    verifySignupForm : `~Please fill the below details to create an account`,
    verifyGoogleAccountScreen : '//XCUIElementTypeStaticText[@name="appdevkato@gmail.com"]',
    clickGoogleAccount : '//XCUIElementTypeStaticText[@name="appdevkato@gmail.com"]',
    freePlanBtn :'~Free Forever to Free (14 Days Trail)'
  };
} else if (browser.isAndroid) {
  loginConstants = {
    welcomeScreenVerify1 : `//*[@text="Welcome to AdaptiveFunnels AI"]`,
    welcomeScreenVerify2 : `//*[@text="Hi there, Enter your credentials to proceed."]`,
    getStartedBtn : "xpath://android.widget.TextView[@text=\"Login\"]",
    googleBtn : `//*[@text="Google"]`,
    loginContentVerify1 : `//*[@text="Welcome to AdaptiveFunnels AI"]`,
    loginContentVerify2 : `//*[@text="Hi there, Enter your credentials to proceed."]`,
    emailField : `//*[@resource-id="login-email"]`,
    passwordField : `//android.view.ViewGroup[3]/android.view.ViewGroup[1]/android.widget.EditText`,
    forgotPasswordField : `//*[@text="Forgot Password?"]`,
    loginBtn : `//*[@text="Login"]`,
    signUpButton : `//*[@text="If you don’t have an account yet ? Sign Up"]`,
    loginBackBtn : `//android.view.ViewGroup[1]/com.horcrux.svg.SvgView`,
    passwordEyeIcon : `//com.horcrux.svg.GroupView/com.horcrux.svg.PathView[2]`,
    emptyFieldCheck : `//*[@text="This field is required"]`,
    bothEmptyMailField : `(//*[@text="This field is required"])[1]`,
    bothEmptyPasswordField : `(//*[@text="This field is required"])[2]`,
    phoneNumerPrefix : `//*[@text="+1"]`,
    emailPrefix : `//com.horcrux.svg.SvgView/com.horcrux.svg.GroupView`,
    phoneNumberLengthValidateMsg : `//*[@text="Please enter a valid Phone Number"]`,
    phoneNumberLengthValidateMsg1 : `//*[@text="Please Enter a valid Phone Number"]`,
    invalidMailCheck1 : `//*[@text="Please enter a valid email address"]`,
    invalidMailCheck : `//*[@text="Please enter a valid email address"]`,
    invalidMailPasswordMail : `//*[@text="Invalid email/password"]`,
    loginVerify : `//*[@text="AI Funnels"]`,
    profileBtn : `//android.widget.ImageView`,
    logoutBtn : `//*[@text="Logout"]`,
    logoutConfrimBtn : `//android.widget.Button[@resource-id="android:id/button1"]`,
    profileScreenVerify : `//*[@text="Profile"]`,
    welcomeScreenVerify3 : `//android.widget.TextView[@text="New to AI Agent?"]`,
    welcomeScreenVerify4 : '//android.widget.TextView[@text="Sign Up"]',
    verifySignupForm : `xpath://android.widget.TextView[@text=\"Please fill the below details to create an account\"]`,
    verifyGoogleAccountScreen : 'id:com.google.android.gms:id/main_title',
    clickGoogleAccount : 'id:com.google.android.gms:id/account_name',
    freePlanBtn :'//*[@text="Continue with free (14 Days Trail)"]'
  };
}
export default loginConstants;