let signupConstants;
if (browser.isIOS) {
  signupConstants = {
    signUpButtonXPath : "~signup",
    createAccountBtn : `~sign-upclick`,
    signupContect1Xpath : "~Welcome!",
    dataEmptyMsgXpath : '~No AI Funnel found',
    dataEmptyMsg1Xpath : '~No Data found',
    WalkthruBtnXpath : '~AI Funnels, tab, 1 of 5',
    EngageBtnXpath : '~Responses, tab, 2 of 5',
    LibraryBtnXpath : '~Library, tab, 4 of 5',
    CommunityBtnXpath : '~Community, tab, 5 of 5',
    signupContect2Xpath : "~Please fill the below details to create an account",
    emptyMsgXpath : `(//XCUIElementTypeStaticText[@name="This field is required"])[1]`,
    choosePlanScreenVerify : `~Choose Your Plan`,
    passwordMismatchMsgXpath : `//XCUIElementTypeStaticText[@name="Password does not match"]`,
    invalidMailMsgXpath : `//XCUIElementTypeStaticText[@name="Please enter a valid email address"]`,
    invalidPhoneMsgXpath : `//XCUIElementTypeStaticText[@name="Please Enter a valid Phone Number"]`,
    checkBoxEmptyMsgXpath : `//XCUIElementTypeStaticText[@name="Please agree to terms and privacy"]`,
    invalidMsgXpath : `//XCUIElementTypeStaticText[@name="Please enter a valid input"]`,
    loginBtnXpath : "~login-click",
    backBtnXpath : `~signup-backclick`,
    usernameXPath : `~firstname-input`,
    firstNameXPath : `~lastname-input`,
    emailXPath1 : `~email-input`,
    phoneXPath2 : `~phone-input`,
    accountTypeBtn : `(//XCUIElementTypeOther[@name="Individual"])[2]`,
    chooseOrg : `//android.widget.TextView[@text="Organization"]`,
    chooseAgent : `//android.widget.TextView[@text="Agency"]`,
    agentField : `(//XCUIElementTypeOther[@name="Agency Name"])[2]/XCUIElementTypeOther[2]/XCUIElementTypeTextField`,
    contractorXPath : `(//XCUIElementTypeOther[@name="Organization Name"])[2]/XCUIElementTypeOther[2]/XCUIElementTypeTextField`,
    passwordXPath : `~password-input`,
    confirmPasswordXPath : `~confirmpassword-input`,
    checkBoxClassName : `~terms-agree`,
    passwordEyeBtn2Xpath : `(//XCUIElementTypeOther[@name="show-password"])[2]`,
    passwordEyeBtnXpath : `(//XCUIElementTypeOther[@name="show-password"])[1]`,
    choosePlanMessageXPath: `//XCUIElementTypeStaticText[@name="Choose the best plan that fits your needs. You can cancel anytime"]`,
    monthlyPlanXPath: "~Monthly",
    yearlyPlanXPath: "~Yearly",
    individualPlanXPath: `//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="Individual Plan Create A.I Funnels | 3 Funnels Total Views website, Email, Text & all customer touch points) 5000/month Managed Analytics Self-Service Dynamic QR - Personalization, Geotargeting & Tracking After Hours Video Customization Read More $ 49 / Month "]`,
    smbPlanXPath: `//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="SMB Plan Create A.I Funnels | 10 Funnels Total Views website, Email, Text & all customer touch points) 50000/month ( Additional views : $10/1000 views ) Managed Analytics Dynamic QR - Personalization, Geotargeting & Tracking After Hours Video Customization Read More $ 299 / Month "]`,
    enterprisePlanXPath: `//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="Enterprise Plan Create AI Funnel Unlimited Total Views website, Email, Text & all customer touch points) Unlimited Advanced Analytics, Do it for You Dedicated Account Manager for Monthly followups After Hours Video Customization Read More $ 999 / Month "]`,
    subscribeButtonXPath: `(//XCUIElementTypeOther[@name="Subscribe"])[2]`,
    individualReadBtn : `(//android.widget.TextView[@text="Read More"])[1]`,
    individualReadBtn1 : `(//android.widget.TextView[@text="Read More"])[2]`,
    individualContent2 : `//android.widget.TextView[@text="Create A.I Funnels | 3 Funnels"]`,
    SMBContent2 : `//android.widget.TextView[@text="Create A.I Funnels | 10 Funnels"]`,
    EnterContent2 : `//android.widget.TextView[@text="Create AI Funnel Unlimited"]`,
    individualContent3 : `//android.widget.TextView[@text="Generate Video Clips Up to 10 clips"]`,
    SMBContent3 : `//android.widget.TextView[@text="Generate Video Clips Unlimited"]`,
    individualContent4 : `//android.widget.TextView[@text="Update A.I Funnels"]`,
    individualContent5 : `//android.widget.TextView[@text="Dynamic Video Funnels"]`,
    individualContent6 : `//android.widget.TextView[@text="Chat Support"]`,
    SMBContent6 : `//android.widget.TextView[@text="Premium Support"]`,
    individualContent7 : `//android.widget.TextView[@text="Managed Analytics Self-Service"]`,
    SMBContent7 : `//android.widget.TextView[@text="Managed Analytics"]`,
    enterContent7 : `//android.widget.TextView[@text="Advanced Analytics, Do it for You"]`,
    individualContent8 : `//android.widget.TextView[@text="Web Dashboard"]`,
    individualContent9 : `//android.widget.TextView[@text="Built in CRM"]`,
    individualContent10 : `//android.widget.TextView[@text="Embed Codes - Website, Video Bots, Contact Us, Landing Pages, Blogs, etc"]`,
    SMBContent10 : `//android.widget.TextView[@text="Embed Codes - Website, Video Bots, Contact Us, Landing Pages, Blogs, etc "]`,
    individualContent11 : `//android.widget.TextView[@text="Email Sharing"]`,
    individualContent12 : `//android.widget.TextView[@text="Social Media Sharing"]`,
    individualContent13 : `//android.widget.TextView[@text="SMS/MMS/Text Sharing"]`,
    individualContent14 : `//android.widget.TextView[@text="3rd party video call integration (Zoom, Google Meet, Teams)"]`,
    individualContent15 : `//android.widget.TextView[@text="Custom Branding Limited"]`,
    SMBContent15 : `//android.widget.TextView[@text="Custom Branding"]`,
    individualContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) 5000/month"]`,
    SMBContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) 50000/month ( Additional views : $10/1000 views )"]`,
    enterContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) Unlimited"]`,
    individualContent17 : `//android.widget.TextView[@text="CRM Integration (Zapier) Self Service"]`,
    SMBContent17 : `//android.widget.TextView[@text="Managed Service (One Time Integration charges apply)"]`,
    individualContent18 : `//android.widget.TextView[@text="Dynamic QR - Personalization, Geotargeting & Tracking"]`,
    individualContent19 : `//android.widget.TextView[@text="After Hours Video Customization"]`,
    individualContent20 : `//android.widget.TextView[@text="Dedicated Account Manager for Monthly followups"]`,
    indiMonthPlan :`//android.widget.TextView[@text="$ 49 / Month "]`,
    indiYearPlan :`//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="Individual Plan Create A.I Funnels | 3 Funnels Total Views website, Email, Text & all customer touch points) 5000/month Managed Analytics Self-Service Dynamic QR - Personalization, Geotargeting & Tracking After Hours Video Customization Read More $ 490 / Year "]`,
    smbMonthPlan :`//android.widget.TextView[@text="$ 299 / Month "]`,
    smbYearPlan :`//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="SMB Plan Create A.I Funnels | 10 Funnels Total Views website, Email, Text & all customer touch points) 50000/month ( Additional views : $10/1000 views ) Managed Analytics Dynamic QR - Personalization, Geotargeting & Tracking After Hours Video Customization Read More $ 2990 / Year "]`,
    enterMonthPlan :`//android.widget.TextView[@text="$ 999 / Month "]`,
    enterYearPlan :`//XCUIElementTypeOther[@name="selectedplan-Basic" and @label="Enterprise Plan Create AI Funnel Unlimited Total Views website, Email, Text & all customer touch points) Unlimited Advanced Analytics, Do it for You Dedicated Account Manager for Monthly followups After Hours Video Customization Read More $ 9990 / Year "]`,
    planReadCloseButton : `//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup`,
    planSwitchBtn : `//XCUIElementTypeSwitch[@name="select-period"]`,
    indiSubcripMContent1 : `~$49.00`,
    indiSubcripMContent2 : `~month`,
    SMBSubcripMContent1 : `~$299.00`,
    SMBSubcripMContent2 : `~month`,
    enterSubcripMContent1 : `~$999.00`,
    enterSubcripMContent2 : `~month`,
    cardField : `~Card number`,
    monthField : `~Expiration`,
    cvcField : `//XCUIElementTypeTextField[@name="CVC"]`,
    nameField : `//XCUIElementTypeTextField[@value="Full name on card"]`,
    subcripConfrimBtn : `~Subscribe`,
    subConfrimContent1 : `~Congratulation!!`,
    subConfrimContent2 : `~Congratulation! Your Payment is success. Please enjoy using AdaptiveFunnels AI service`,
    backToHomeBtn : `(//XCUIElementTypeOther[@name="Back Home"])[2]`,
    paymentSuccess : `~Payment Successful`,
    stripeBack : `~Back to Walkthru, Inc`,
    indiSubcripYContent1 : `~$490.00`,
    indiSubcripYContent2 : `~year`,
    SMBSubcripYContent1 : `~$2,990.00`,
    SMBSubcripYContent2 : `~year`,
    enterSubcripYContent1 : `~$9,990.00`,
    enterSubcripYContent2 : `~year`,
    profileBtn : `~home-profile`,
    manageSubcriptionBtn : `~Manage Subscriptionclick`,
    freePlanContent : `~You are currently on the free plan (14 Days Trail)`
  };
} else if (browser.isAndroid) {
  signupConstants = {
    signUpButtonXPath : "xpath://android.widget.TextView[@text=\"Sign Up\"]",
    signupContect1Xpath : "xpath://android.widget.TextView[@text=\"Welcome!\"]",
    dataEmptyMsgXpath : '//android.widget.TextView[@text="No AI Funnel found"]',
    dataEmptyMsg1Xpath : '//android.widget.TextView[@text="No Data found"]',
    WalkthruBtnXpath : '//android.widget.TextView[@text="AI Funnels"]',
    EngageBtnXpath : '//android.widget.TextView[@text="Inbox"]',
    LibraryBtnXpath : '//android.widget.TextView[@text="Library"]',
    CommunityBtnXpath : '//android.widget.TextView[@text="Community"]',
    signupContect2Xpath : "xpath://android.widget.TextView[@text=\"Please fill the below details to create an account\"]",
    emptyMsgXpath : "xpath://android.widget.TextView[@text=\"This field is required\"]",
    choosePlanScreenVerify : `//android.widget.TextView[@text="Choose Your Plan"]`,
    passwordMismatchMsgXpath : "xpath://android.widget.TextView[@text=\"Password does not match\"]",
    invalidMailMsgXpath : "xpath://android.widget.TextView[@text=\"Please enter a valid email address\"]",
    invalidPhoneMsgXpath : "xpath://android.widget.TextView[@text=\"Please Enter a valid Phone Number\"]",
    checkBoxEmptyMsgXpath : "xpath://android.widget.TextView[@text=\"Please agree to terms and privacy\"]",
    invalidMsgXpath : "xpath://android.widget.TextView[@text=\"Please enter a valid input\"]",
    loginBtnXpath : "xpath://android.widget.TextView[@text=\"Already have an account? Login\"]",
    backBtnXpath : `//android.view.ViewGroup[@resource-id="signup-backclick"]`,
    usernameXPath : `//android.widget.EditText[@resource-id="firstname-input"]`,
    firstNameXPath : `//android.widget.EditText[@resource-id="lastname-input"]`,
    emailXPath1 : `//android.widget.EditText[@resource-id="email-input"]`,
    phoneXPath2 : `//android.widget.EditText[@resource-id="phone-input"]`,
    accountTypeBtn : `//android.widget.TextView[@text="Individual"]`,
    chooseOrg : `//android.widget.TextView[@text="Organization"]`,
    chooseAgent : `//android.widget.TextView[@text="Agency"]`,
    contractorXPath : "//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]/android.view.ViewGroup/android.widget.EditText",
    passwordXPath : `//android.widget.EditText[@resource-id="password-input"]`,
    confirmPasswordXPath : `//android.widget.EditText[@resource-id="confirmpassword-input"]`,
    checkBoxClassName : `//android.widget.CheckBox[@resource-id="terms-agree"]`,
    passwordEyeBtnXpath : "xpath://android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[7]/android.view.ViewGroup[2]",
    choosePlanMessageXPath: "xpath://android.widget.TextView[@text=\"Choose the best plan that fits your needs. You can cancel anytime\"]",
    monthlyPlanXPath: "xpath://android.widget.TextView[@text=\"Monthly\"]",
    yearlyPlanXPath: "xpath://android.widget.TextView[@text=\"Yearly\"]",
    individualPlanXPath: "xpath://android.widget.TextView[@text=\"Individual Plan\"]",
    smbPlanXPath: "xpath://android.widget.TextView[@text=\"SMB Plan\"]",
    enterprisePlanXPath: "xpath://android.widget.TextView[@text=\"Enterprise Plan\"]",
    subscribeButtonXPath: "xpath://android.widget.TextView[@text=\"Subscribe\"]",
    individualReadBtn : `(//android.widget.TextView[@text="Read More"])[1]`,
    individualReadBtn1 : `(//android.widget.TextView[@text="Read More"])[2]`,
    individualContent2 : `//android.widget.TextView[@text="Create A.I Funnels | 3 Funnels"]`,
    SMBContent2 : `//android.widget.TextView[@text="Create A.I Funnels | 10 Funnels"]`,
    EnterContent2 : `//android.widget.TextView[@text="Create AI Funnel Unlimited"]`,
    individualContent3 : `//android.widget.TextView[@text="Generate Video Clips Up to 10 clips"]`,
    SMBContent3 : `//android.widget.TextView[@text="Generate Video Clips Unlimited"]`,
    individualContent4 : `//android.widget.TextView[@text="Update A.I Funnels"]`,
    individualContent5 : `//android.widget.TextView[@text="Dynamic Video Funnels"]`,
    individualContent6 : `//android.widget.TextView[@text="Chat Support"]`,
    SMBContent6 : `//android.widget.TextView[@text="Premium Support"]`,
    individualContent7 : `//android.widget.TextView[@text="Managed Analytics Self-Service"]`,
    SMBContent7 : `//android.widget.TextView[@text="Managed Analytics"]`,
    enterContent7 : `//android.widget.TextView[@text="Advanced Analytics, Do it for You"]`,
    individualContent8 : `//android.widget.TextView[@text="Web Dashboard"]`,
    individualContent9 : `//android.widget.TextView[@text="Built in CRM"]`,
    individualContent10 : `//android.widget.TextView[@text="Embed Codes - Website, Video Bots, Contact Us, Landing Pages, Blogs, etc"]`,
    SMBContent10 : `//android.widget.TextView[@text="Embed Codes - Website, Video Bots, Contact Us, Landing Pages, Blogs, etc "]`,
    individualContent11 : `//android.widget.TextView[@text="Email Sharing"]`,
    individualContent12 : `//android.widget.TextView[@text="Social Media Sharing"]`,
    individualContent13 : `//android.widget.TextView[@text="SMS/MMS/Text Sharing"]`,
    individualContent14 : `//android.widget.TextView[@text="3rd party video call integration (Zoom, Google Meet, Teams)"]`,
    individualContent15 : `//android.widget.TextView[@text="Custom Branding Limited"]`,
    SMBContent15 : `//android.widget.TextView[@text="Custom Branding"]`,
    individualContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) 5000/month"]`,
    SMBContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) 50000/month ( Additional views : $10/1000 views )"]`,
    enterContent16 : `//android.widget.TextView[@text="Total Views website, Email, Text & all customer touch points) Unlimited"]`,
    individualContent17 : `//android.widget.TextView[@text="CRM Integration (Zapier) Self Service"]`,
    SMBContent17 : `//android.widget.TextView[@text="Managed Service (One Time Integration charges apply)"]`,
    individualContent18 : `//android.widget.TextView[@text="Dynamic QR - Personalization, Geotargeting & Tracking"]`,
    individualContent19 : `//android.widget.TextView[@text="After Hours Video Customization"]`,
    individualContent20 : `//android.widget.TextView[@text="Dedicated Account Manager for Monthly followups"]`,
    indiMonthPlan :`//android.widget.TextView[@text="$ 49 / Month "]`,
    indiYearPlan :`//android.widget.TextView[@text="$ 490 / Year "]`,
    smbMonthPlan :`//android.widget.TextView[@text="$ 299 / Month "]`,
    smbYearPlan :`//android.widget.TextView[@text="$ 2990 / Year "]`,
    enterMonthPlan :`//android.widget.TextView[@text="$ 999 / Month "]`,
    enterYearPlan :`//android.widget.TextView[@text="$ 9990 / Year "]`,
    planReadCloseButton : `//android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup`,
    planSwitchBtn : `//android.widget.Switch[@resource-id="select-period"]`,
    indiSubcripMContent1 : `//android.widget.TextView[@text="$49.00"]`,
    indiSubcripMContent2 : `//android.widget.TextView[@text="per month"]`,
    SMBSubcripMContent1 : `//android.widget.TextView[@text="$299.00"]`,
    SMBSubcripMContent2 : `//android.widget.TextView[@text="per month"]`,
    enterSubcripMContent1 : `//android.widget.TextView[@text="$999.00"]`,
    enterSubcripMContent2 : `//android.widget.TextView[@text="per month"]`,
    cardField : `(//android.view.View[@text="Pay with card"])[2]/android.view.View/android.view.View[2]/android.view.View/android.view.View[1]/android.view.View[1]/android.widget.EditText`,
    monthField : `(//android.view.View[@text="Pay with card"])[2]/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View/android.widget.EditText`,
    cvcField : `(//android.view.View[@text="Pay with card"])[2]/android.view.View/android.view.View[2]/android.view.View/android.view.View[3]/android.view.View[1]/android.widget.EditText`,
    nameField : `(//android.view.View[@text="Pay with card"])[2]/android.view.View/android.view.View[3]/android.view.View/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.widget.EditText`,
    subcripConfrimBtn : `//android.widget.Button[@text="Subscribe"]`,
    subConfrimContent1 : `//android.widget.TextView[@text="Congratulation!!"]`,
    subConfrimContent2 : `//android.widget.TextView[@text="Congratulation! Your Payment is success. Please enjoy using AdaptiveFunnels AI service"]`,
    backToHomeBtn : `//android.widget.TextView[@text="Back Home"]`,
    paymentSuccess : `//android.widget.TextView[@text="Payment Successful"]`,
    stripeBack : `//android.widget.TextView[@text="Back"]`,
    indiSubcripYContent1 : `//android.widget.TextView[@text="$490.00"]`,
    indiSubcripYContent2 : `//android.widget.TextView[@text="per year"]`,
    SMBSubcripYContent1 : `//android.widget.TextView[@text="$2,990.00"]`,
    SMBSubcripYContent2 : `//android.widget.TextView[@text="per year"]`,
    enterSubcripYContent1 : `//android.widget.TextView[@text="$9,990.00"]`,
    enterSubcripYContent2 : `//android.widget.TextView[@text="per year"]`,
    profileBtn : `//android.view.ViewGroup[@resource-id="home-profile"]`,
    manageSubcriptionBtn : `//android.view.ViewGroup[@resource-id="Manage Subscriptionclick"]`,
    freePlanContent : `//android.widget.TextView[@text="You are currently on the free plan (14 Days Trail)"]`
  };
}
export default signupConstants;